### ISSUE TITLE
Retrieving the attributes of `.sas7bdat`

### ISSUE THREAD

**Issue by botsp** [BioStatMatt/sas7bdat#18]
Hi,
Does this package support retrieving attributes of SAS datasets, such as Sort Information? Or is there a possibility that this feature will be developed in the future?

(I should submit this issue as a question, it's not an usage issue about the package, thanks for your attention)

**Comment by BioStatMatt** [comment]
That feature is not implemented. This package is in maintenance only.

Regards,
Matt

**Comment by botsp** [comment]
Thank you Matt, understood.
